# Generated by Django 5.1.1 on 2024-10-01 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='blocked',
            field=models.ManyToManyField(related_name='blocked_by', through='friends.BlockedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='friends',
            field=models.ManyToManyField(through='friends.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
